version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: /stop.sh
      timeout: 300
      runas: ec2-user
  # During the ApplicationStart deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ApplicationStart:
    - location: /start.sh
      timeout: 300
      runas:  ec2-user
  # During the ValidateService deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ValidateService:
    - location: /validate.sh
      timeout: 300
      runas: ec2-user