spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: "bloggerator"
api:
  base-url: https://jsonplaceholder.typicode.com/


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    shutdown:
      enabled: true
info:
  app:
    name: "Bloggerator"
    description: "My sweet blogging app"